version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: jobportal_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobportal
      POSTGRES_USER: jobportal_user
      POSTGRES_PASSWORD: jobportal_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - jobportal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobportal_user -d jobportal"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend Django
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobportal_backend
    restart: unless-stopped
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://jobportal_user:jobportal_password@db:5432/jobportal
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jobportal_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jobportal_frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "4200:80"
    depends_on:
      - backend
    networks:
      - jobportal_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  backend_static:
    driver: local
  backend_media:
    driver: local

networks:
  jobportal_network:
    driver: bridge 