# Generated by Django 4.2.7 on 2025-06-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En Revisión'), ('interviewed', 'Entrevistado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', help_text='Application status', max_length=20)),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter from applicant')),
                ('resume_url', models.URLField(blank=True, help_text='URL to resume/CV')),
                ('notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('location', models.CharField(help_text='Job location', max_length=100)),
                ('category', models.CharField(choices=[('technology', 'Tecnología'), ('marketing', 'Marketing'), ('sales', 'Ventas'), ('design', 'Diseño'), ('finance', 'Finanzas'), ('human_resources', 'Recursos Humanos'), ('customer_service', 'Atención al Cliente'), ('operations', 'Operaciones'), ('other', 'Otro')], default='other', help_text='Job category', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary', max_digits=10, null=True)),
                ('requirements', models.TextField(blank=True, help_text='Job requirements and qualifications')),
                ('benefits', models.TextField(blank=True, help_text='Job benefits and perks')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the job posting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
